### ISSUE TITLE
Failed fetch when running container

### ISSUE THREAD

**Issue by Blair-Young** [pyannote/pyannote-video#13]
Running the command: docker build -t pyannote/video .

Returns this:

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/p/python-pip/python-pip-whl_1.5.4-1ubuntu3_all.deb  404  Not Found [IP: 91.189.88.162 80]

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/p/python-pip/python-pip_1.5.4-1ubuntu3_all.deb  404  Not Found [IP: 91.189.88.162 80]

**Comment by hbredin** [comment]
This might have been fixed by @yaochx in #10. 
Can you try again using `develop` branch?

**Comment by Blair-Young** [comment]
thanks, first glance it looks like it was built correctly, however I am now getting a docker error with this command:

docker run -p 80:8888 -v pyannote-video/scripts:/scripts
                       -v pyannote-data:/data 
                      -v pyannote-video/doc:/notebooks pyannote/video

docker: Error response from daemon: create pyannote-video/doc: "pyannote-video/doc" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed.

I've managed to fix this error but now when I finally open up the localhost it's blank, when I create a new notebook and run %run /pyannote-video/scripts/pyannote-structure.py --help:

I get ERROR:root:File `u'/scripts/pyannote-structure.py'` not found

**Comment by yaochx** [comment]
please refer to #11

**Comment by hbredin** [comment]
Thanks @yaochx.
I just made a new release (1.3.12) so that your various fixes are in the master branch.

**Comment by hbredin** [comment]
Closing, as the original issue is now solved.

Open a new issue if new README in release 1.3.12 does not fix your problem.
