### ISSUE TITLE
Hard version requirement for dlib==19.4.0 breaks install on OSX

### ISSUE THREAD

**Issue by peterk** [pyannote/pyannote-video#28]
#### Description
Dlib 19.4.0 can not be pip installed on OSX it seems. Later versions are OK. This error prevents installing pyannotate-video on OSX High Sierra.

#### Steps/Code to Reproduce
1. Clone pyannotate-video to a folder on OSX High Sierra machine.
2. run python setup.py install

#### Expected Results
Should install

#### Actual Results
```
Running dlib-19.4.0/setup.py -q bdist_egg --dist-dir /var/folders/j2/hr94sgx55wd04f7j8kb63y9c0000gp/T/easy_install-jpo1q99f/dlib-19.4.0/egg-dist-tmp-mg4da5bn
error: Setup script exited with error: cmake build failed!
```

#### Versions
pyannote.algorithms==0.7.3
pyannote.core==1.2
pyannote.parser==0.7.1
pyannote.video==1.5.1+0.g5445850.dirty

**Comment by hbredin** [comment]
Thanks for reporting this issue which I cannot reproduce in El Capitan.
I don't remember why exactly I decided to go with specific versions of `dlib`.

Does it work with later versions?
It would be great to also use the latest GPU-accelerated face detectors that were added recently in `dlib`...
