### ISSUE TITLE
Why mark scene clustering unavailable? It seems work well

### ISSUE THREAD

**Issue by ghost** [pyannote/pyannote-video#29]
#### Description

This is more like a general question than a bug so I will close it as soon as the discussion ends or waiting long with no response.

When I studied the source codes in _**pyannote-structure.py**_  I noticed the **do_scene** function was commented out and marked unavailable for now. But when I added them back and used scenes function in Thread, the clustering did work well and generated a higher level structure on top of thread. So I am just curious why that part is marked unavailable for now? Is it still in progress for debugging or for a better performance? 

#### Steps/Code to Reproduce
<!--
Example:

```
with open(threads, 'r') as fp:
        threads = pyannote.core.json.load(fp)
    raise NotImplementedError('Not yet available')
    # scenes = Scene(video, thread=threads, verbose=verbose)
    # with open(output, 'w') as fp:
    #     pyannote.core.json.dump(scenes, fp)
```

**Comment by hbredin** [comment]
It has been a long time since I haven’t worked on this project. 
I am not sure why I commented this part out. 

Feel free to pull a request adding it back. 
Ideally, this would also come with some kind of benchmark to evaluate its performance, and also some kind of documentation...
