### ISSUE TITLE
did not match c++ signature

### ISSUE THREAD

**Issue by FFZhang1231** [pyannote/pyannote-video#30]
Thank you very much for your sharing.

I have two questions: (1) Which path should I place the pyannote-video and dlib-models files?
(2) i always have the error: Boost.python.ArgumentError: 
'Python argument types in shape_predictor.__init__(shape_predictor,str) 
did not match c++ signature:
__init__(boost:python::api::object,std::string)
__init__(_object*)'
when i run 
'!pyannote-face.py extract --verbose pyannote-data/TheBigBangTheory.mkv \
                                    pyannote-data/TheBigBangTheory.track.txt \
                                    dlib-models/shape_predictor_68_face_landmarks.dat \
                                    dlib-models/dlib_face_recognition_resnet_model_v1.dat \
                                    pyannote-data/TheBigBangTheory.landmarks.txt \
                                    pyannote-data/TheBigBangTheory.embedding.txt'

Thank you very much.

**Comment by hbredin** [comment]
1. Use any path you want -- `pyannote-face.py` expects absolute path to dlib models anyway. 
2. Seems like an issue with `dlib`. I probably won't be able to help...
