### ISSUE TITLE
TypeError: topological_sort() got an unexpected keyword argument 'nbunch'`

### ISSUE THREAD

**Issue by stefanxinhong** [pyannote/pyannote-video#31]
Thank you for your sharing.
i follow [http://nbviewer.jupyter.org/github/pyannote/pyannote-video/blob/master/doc/getting_started.ipynb](url).
 when i run 'result = clustering(face_tracks, features=embeddings
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-26d56cfd42c6> in <module>()
----> 1 result = clustering(face_tracks, features=embeddings)

~/Downloads/soft/anaconda3/envs/pyannote/lib/python3.5/site-packages/pyannote/algorithms/clustering/hac/hac.py in __call__(self, starting_point, features, callback)
    209         # default behavior is return the result of the penultimate iteration
    210         # (unless stopping_criterion.finalize is overiden)
--> 211         return self.stopping_criterion.finalize(parent=self)

~/Downloads/soft/anaconda3/envs/pyannote/lib/python3.5/site-packages/pyannote/algorithms/clustering/hac/stop.py in finalize(self, parent)
    132         # either it reached the stopping criterion...
    133         if self.reached(parent=parent):
--> 134             return parent.history.penultimate()
    135 
    136         # ... or there is nothing left to merge

~/Downloads/soft/anaconda3/envs/pyannote/lib/python3.5/site-packages/pyannote/algorithms/clustering/hac/history.py in penultimate(self)
    118         """Get clustering status after penultimate iteration"""
    119         if len(self) > 1:
--> 120             return self[-2]
    121         else:
    122             return self.last()

~/Downloads/soft/anaconda3/envs/pyannote/lib/python3.5/site-packages/pyannote/algorithms/clustering/hac/history.py in __getitem__(self, n)
    165         mapping = {}
    166         for clusters in connected_components(g.to_undirected()):
--> 167             clusters = topological_sort(g, nbunch=clusters, reverse=True)
    168             for cluster in clusters[1:]:
    169                 mapping[cluster] = clusters[0]

TypeError: topological_sort() got an unexpected keyword argument 'nbunch'`

``
Thanks a lot!

**Comment by stefanxinhong** [comment]
which version of **_networkx_** package have used m in code?

**Comment by hbredin** [comment]
I believe this is a bug in `pyannote.algorithms`, not `pyannote.video`.
Please refer to https://github.com/pyannote/pyannote-algorithms/issues/6.
