### ISSUE TITLE
FaceClustering.clustering returns a ValueError

### ISSUE THREAD

**Issue by yasumori** [pyannote/pyannote-video#34]
#### Description
I was following the tutorial of pyannote-video, but it failed at the FaceClustering section.
The data I used is attached below ('my_embedding.txt').
[my_embedding.txt](https://github.com/pyannote/pyannote-video/files/2262672/my_embedding.txt)

I've looked into the error, and the similarity matrix seemed to have a key "(10, 22)", which caused a ValueError.
Its value could be retrieved with "model._similarity.get((10, 22))".
Therefore, it could be an error with the pop method of sortedDict, but I could be wrong.
I'd appreciate if you could investigate this.

#### Steps/Code to Reproduce
```
from pyannote.video.face.clustering import FaceClustering
c = FaceClustering()
f, e = c.model.preprocess('my_embedding.txt')
r = c(f, e)
```

#### Expected Results
Code runs without a value error.

#### Actual Results
```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    r = c(f, e)
  File "/usr/local/lib/python3.6/dist-packages/pyannote/algorithms/clustering/hac/hac.py", line 204, in __call__
    for i, current_state in enumerate(self._iterate()):
  File "/usr/local/lib/python3.6/dist-packages/pyannote/algorithms/clustering/hac/hac.py", line 172, in _iterate
    self.model.update(clusters, into, parent=self)
  File "/usr/local/lib/python3.6/dist-packages/pyannote/algorithms/clustering/hac/model.py", line 164, in update
    self._similarity.pop((i, j), default=None)
  File "/usr/local/lib/python3.6/dist-packages/sortedcontainers/sorteddict.py", line 415, in pop
    self._list_remove(key)
  File "/usr/local/lib/python3.6/dist-packages/sortedcontainers/sortedlist.py", line 2021, in remove
    raise ValueError('{0!r} not in list'.format(value))
ValueError: (10, 22) not in list
```

This shows that (22, 10) is in keys, but could not be popped. 
```
>>> (22, 10) in c.model._similarity.keys()
True
>>> c.model._similarity.pop((22, 10))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/sortedcontainers/sorteddict.py", line 415, in pop
    self._list_remove(key)
  File "/usr/local/lib/python3.6/dist-packages/sortedcontainers/sortedlist.py", line 2021, in remove
    raise ValueError('{0!r} not in list'.format(value))
ValueError: (22, 10) not in list
```

#### Versions
pyannote.algorithms==0.8
pyannote.core==1.4
pyannote.parser==0.7.1
pyannote.video==1.6.2

**Comment by yasumori** [comment]
I've made a fix for this in: https://github.com/pyannote/pyannote-algorithms/pull/8

I wasn't sure about the reason for the error I got, but perhaps it was due to the "pop" method of ValueSortedVector inside the clustering iteration.

Instead of calling "pop", this commit opens a new ValueSortedVector, adds only necessary indexes to the similarity matrix, and replaces the old matrix with the new one.

**Comment by hbredin** [comment]
Thanks for reporting this but I cannot reproduce the error.

Can you try with the latest version of `sortedcollections` and `sortedcontainers`?

**Comment by yasumori** [comment]
Thank you for checking the issue. I ran the same script with the following versions of the libraries.
I believe these are the latest versions of the libraries:
sortedcollections==1.0.1
sortedcontainers==2.0.4

I didn't encounter the same issue, so I think I was using the older versions of those libraries earlier.
I'm going to close this issue, and the other one in pyannote.algorithms, as it is solved.

**Comment by hbredin** [comment]
Thanks anyway!
