### ISSUE TITLE
Setup script exited with error: Cannot find cmake in the path. - During Installation

### ISSUE THREAD

**Issue by zeta274** [pyannote/pyannote-video#4]
Processing dlib-18.17.100.zip
Writing /tmp/easy_install-IL23cW/dlib-18.17.100/setup.cfg
Running dlib-18.17.100/setup.py -q bdist_egg --dist-dir /tmp/easy_install-IL23cW/dlib-18.17.100/egg-dist-tmp-ebUsHT
error: Setup script exited with error: cmake configuration failed!

This was in response to sudo python setup.py install with the latest version of this package. Any help will be super appreciated.

**Comment by hbredin** [comment]
Looks like an issue with the installation of `dlib`.
Is `cmake` available on your system?

**Comment by zeta274** [comment]
Yup, and it seems to be working fine. Are there other CMake related dependencies that I wouldn't think to install?

**Comment by f0t0n** [comment]
Seems the problem with the comment of empty line [here](https://github.com/pyannote/pyannote-video/blob/master/pyannote/video/face/openface_server.lua.py#L2). At least it complains about it and says it's syntax error.

See: http://stackoverflow.com/questions/37501761/installing-python-package-issue-with-cmake-configuration?noredirect=1#comment62503995_37501761

**Comment by f0t0n** [comment]
Initial error in stack trace (listed at SO as well):

```
byte-compiling build/bdist.linux-x86_64/egg/pyannote/video/face/openface_server.lua.py to openface_server.lua.pyc
  File "build/bdist.linux-x86_64/egg/pyannote/video/face/openface_server.lua.py", line 2
    --
     ^
SyntaxError: invalid syntax
```

**Comment by heman4t** [comment]
Me too getting the same error.

**Comment by hbredin** [comment]
ee3a93e7751e656a595985cac27ec13a40165622 may have solved the problem. Can you try again with latest release?

**Comment by heman4t** [comment]
Its working fine now. :+1: 

Additional note for noobs like me:
1. Don't forget to clear build, dist, pyannote.video.egg-info before rebuilding/reinstalling by using this command in linux `sudo rm -rf build/* dist/* pyannote.video.egg-info/*`
2. Install torch before this. (I had no idea earlier) :speak_no_evil: 

EDIT: Created a wiki page https://github.com/pyannote/pyannote-video/wiki.

**Comment by hbredin** [comment]
Closing this issue as the installation error (the point of this issue) seems to be solved now.

Thanks @heman4t  for the wiki link -- but I am going to remove the wiki completely for now as I do not have the manpower to maintain it. See discussion in issue #5 for more information on how to use `pyannote-video` command line tools.
