### ISSUE TITLE
Need a little documentation

### ISSUE THREAD

**Issue by heman4t** [pyannote/pyannote-video#5]
It's silly but I don't know what to do after installation. What parameters do I need to pass?

Using `pyannote-structure.py --help`, I have tried:
`pyannote-structure.py shot /dev/video0 ~/aa.json`
and in `pyannote-face.py --help`
`pyannote-face.py track /dev/video0 ~/shot.json ~/output`

here aa.json, shot.json and output are blank files. From where will I get them? :no_mouth: 

I must mention> I am a noob. I tried https://github.com/cmusatyalab/openface/. Liked it very much. Now want to recognize face from real-time video streams like security camera. But it is not clear what to do with "pyannote-video" which is based upon openface.

**Comment by hbredin** [comment]
I just added a link in README to the "getting started" guide in latest release (1.3.11) 
See https://github.com/pyannote/pyannote-video

FYI, currently `pyannote-video` does not allow live stream processing nor face recognition.
It only allows batch (aka offline) face clustering.

**Comment by heman4t** [comment]
Thank you. :bow:
