### ISSUE TITLE
Error while installing lib on Python 3.8.10

### ISSUE THREAD

**Issue by coalus** [pyannote/pyannote-video#50]
ERROR: Could not find a version that satisfies the requirement opencv-python==3.4.1.15 (from versions: 3.4.0.14, 3.4.8.29, 3.4.9.31, 3.4.9.33, 3.4.10.35, 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.14.51, 3.4.14.53, 3.4.15.55, 3.4.16.57, 3.4.16.59, 4.1.2.30, 4.2.0.32, 4.2.0.34, 4.3.0.36, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.2.52, 4.5.2.54, 4.5.3.56, 4.5.4.58, 4.5.4.60)
ERROR: No matching distribution found for opencv-python==3.4.1.15
While installing pyannote-video
(pip install pyannote-video)
Ubuntu 20.04
Python 3.8.10

**Comment by hbredin** [comment]
Might be related to https://github.com/pyannote/pyannote-video/issues/38
